### ISSUE TITLE
Add USA charities

### ISSUE THREAD

**Issue by isikm** [aeneas1163/EffectiveNavigation#11]
make app usable in US phones

**Comment by aeneas1163** [comment]
http://www.cancer.org/involved/morewaystogive/fight-cancer-with-your-mobile-phone

**Comment by aeneas1163** [comment]
https://www.wfp.org/donatebytext

**Comment by aeneas1163** [comment]
http://www.redcross.org/support/donating-fundraising/donations/text-messaging

**Comment by aeneas1163** [comment]
http://m.savethechildren.org/site/c.ckLQKcOTLjK8E/b.8776987/k.9D46/Text_Alerts.htm

**Comment by aeneas1163** [comment]
https://secure.savethechildren.org/site/c.ckLQKcOTLjK8E/b.9142417/k.C189/Global_Action_Fund/apps/ka/sd/donorcustom.asp?kntaw49309=DF2A26F76AE04A05B605D3D203F65181

**Comment by aeneas1163** [comment]
done
